### ISSUE TITLE
Release new version

### ISSUE THREAD

**Issue by phls** [hisashim/docdiff#25]
Hi,

Could you release this software as a new version?

There are a lot of changes since 2011 (0.5.0).

If you do it, I can update the debian package too.

best regards,

**Comment by hisashim** [comment]
Thanks a lot, I'll try releasing 0.6.0.

**Comment by hisashim** [comment]
@phls I've just pushed v0.6.0
https://github.com/hisashim/docdiff/releases/tag/v0.6.0

Changes from v0.5.0 are:

* User-visible changes:
  - Drop support for Ruby 1.8 (thanks to takahashim).
  - Fix various encoding problems (thanks to takahashim).
  - Add CP932 (Windows-31J) support through a new option `--cp932` (thanks to emasaka).
  - Introduce readme.md, which will obsolete readme.html eventually (thanks to takahashim).
* Developer-related changes:
  - Use Mutex#synchronize instead of Thread.exclusive (thanks to hsbt).
  - Remove JIS0208.TXT to comply with its terms of use (thanks to kmuto).
  - Introduce top-level class DocDiff to avoid name conflict (thanks to hibariya).

I guess changes from Debian package 0.5.0+git20160313-2 seem like:

- Version bump, a news entry in readme.html, and an update to acknowledgements in readme.md (#26, #27)
- Fix to Rakefile (#24)
- Fix to readme.md (#23)
- Drop support for Ruby 1.8 (#22)
- Encoding-related fixes (#18, #19, #21)

I believe the application works and hope this will do for the moment.

If you're okay with this, this will be version 0.6.0.
Please let me know if there are any problems.

Thank you for maintaining the Debian package.

**Comment by emasaka** [comment]
Thank you to release docdiff 0.6.0.  And I want to install docdiff 0.6.0 via rubygems.org.  Please upload it to rubygems.org.

**Comment by hisashim** [comment]
@emasaka Thank you for your suggestion, and excuse me for late reply.
My notification settings were broken.

I've just uploaded a gem to https://rubygems.org/gems/docdiff .
Please let me know if there are problems, as I'm not used to gems.
